### ISSUE TITLE
Cannot find module '@clickbar/dot-diver' or its corresponding type declarations. ts(2307)

### ISSUE THREAD

**Issue by Vanilagy** [clickbar/dot-diver#15]
There seems to be an issue with the declaration file or how it is detected. I found this bug in an existing project where it caused Dependabot to fail, but was able to reproduce it in a minimal, new project:

![CleanShot 2023-11-06 at 13 40 06](https://github.com/clickbar/dot-diver/assets/1696106/d1d59206-2e59-4f66-ae53-1b155fb1347d)

**Comment by saibotk** [comment]
Thanks for reporting this!
